### ISSUE TITLE
(refactored branch) Defining multiple output sections does not cause an error.

### ISSUE THREAD

**Issue by harada-toshi** [ossc-db/pgaudit#29]
## Overview

Defining multiple output sections does not cause an error.
In Readme.md, it is described as follows.

> At most one output-section can be written at the beginning of the file.

However, describing two output sections does not cause an error, and the server starts.
Is it a bug on the program side or an error in the description in Readme.md?

## config file sample

```
[output]
        logger = 'serverlog'
        level = 'NOTICE'
[output]
        logger = 'serverlog'
        level = 'INFO'

# SQL
[rule]
        format = '%t,%d,%u,%p,%v,%statement_id,%sub_statement_id,%class,%command_tag,%object_type,%object_name,%command_text'
        class = 'READ,WRITE,DDL,ROLE,FUNCTION,MISC'

```

## PostgreSQL launch log

```
$ pg_ctl -w start -D ~/pgdata/9.6-pgaudit/
waiting for server to start....LOG:  log_catalog = 1
LOG:  log_level_string = (null)
LOG:  log_level = 15
LOG:  log_parameter = 0
LOG:  log_statement_once = 0
LOG:  log_for_test = 0
LOG:  role =
LOG:  logger = serverlog
LOG:  facility = (null)
LOG:  priority = (null)
LOG:  ident = (null)
LOG:  option = (null)
LOG:  pathlog = (null)
LOG:  Rule 0
LOG:      BMP class = 500
LOG:  pgaudit extension initialized
}{}LOG:  database system was shut down at 2017-02-22 15:33:10 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
LOG:  connection received: host=[local]
LOG:  connection authorized: user=nuko database=postgres
FATAL:  role "nuko" does not exist
 done
server started
```

**Comment by harada-toshi** [comment]
Similar problems

- Behavior when multiple option sections are written should also be written in Readme.md.
- In the current version, when multiple option sections are written, the last described contents are valid.

**Comment by MasahikoSawada** [comment]
Commit 5e3fedef6fae1c56aeb62dbea11336765aead61f should fix this issue; I've changed it to disallow to define output and option section more than one time. please confirm it.

**Comment by harada-toshi** [comment]
Thanks!
I confirmed that it is an error when multiple output-sections are written.
