### ISSUE TITLE
(refactored branche) Question: Does the parameter name in the setting file allow only lowercase letters?

### ISSUE THREAD

**Issue by harada-toshi** [ossc-db/pgaudit#35]
# Overview
* Does the parameter name in the setting file allow only lowercase letters?
* In "advanced branch", parameter names allowed both uppercase and lowercase letters.
* If you only accept lowercase letters in refactored version parameter names, you should note it in Readme.md.

# Example: LOG_CATALOG
## Config file sample

```
[output]
        logger = 'serverlog'
        level   = 'LOG'

[option]
        role = 'auditor'
        log_catalog = on
        LOG_CATALOG = off

[rule]
        format = '%t,%d,%u,%p,%v,%statement_id,%sub_statement_id,%class,%command_tag,%object_type,%object_name,%command_text'
        class = 'READ,WRITE,DDL,ROLE,FUNCTION,MISC'
```

## PostgreSQL Launch log
```
$ pg_ctl -w -D ~/pgdata/9.6-pgaudit/ start
waiting for server to start....FATAL:  error invalid token "L" in "option section"
LOG:  database system is shut down
 stopped waiting
pg_ctl: could not start server
Examine the log output.
```

**Comment by MasahikoSawada** [comment]
Thanks, good point.
Commit 7449e84b718467edcf0c72f1e0ba1e5e7d164688 changes pgaudit parse case-insensitive. Now we can also set section name in upper case. Please confirm it.

**Comment by harada-toshi** [comment]
Thank you very much.
This action no longer causes an error.

However, we have another problem occurs.
In this commit version, parameters written in uppercase letters are ignored.
(Details will be reported on issue #37 )

**Comment by MasahikoSawada** [comment]
Thanks. Since you opened that issue as separated issue, close this.
