### ISSUE TITLE
(refactored branch) Behavior when you specify an invalid timestamp literal

### ISSUE THREAD

**Issue by harada-toshi** [ossc-db/pgaudit#47]
# Overview
* If an illegal timestamp literal is specified, it will not result in an error and the timestamp interval that can not hit (possibly) will be implied.
* If an illegal timestamp literal is specified, either action is required.
   * If an illegal timestamp literal is specified, abort the startup of the PostgreSQL server as an error. This is, to follow the behavior of the description error of other configuration files.
   * Describe the current behavior in Readme.md.

# Config file sample

```
[output]
        logger = 'serverlog'

# SQL(1)
[rule]
        class = 'READ'
        timestamp = 'invalid-format'
```

# PostgreSQL launch log

```
$ pg_ctl -D ~/pgdata/9.6-pgaudit/ start
server starting
$ LOG:  log_catalog = 1
LOG:  log_level_string = (null)
LOG:  log_level = 15
LOG:  log_parameter = 0
LOG:  log_statement_once = 0
LOG:  log_for_test = 0
LOG:  role =
LOG:  logger = serverlog
LOG:  facility = (null)
LOG:  priority = (null)
LOG:  ident = (null)
LOG:  option = (null)
LOG:  pathlog = (null)
LOG:  Rule 0
LOG:      TMS timestamp = -1777955776
LOG:      TMS timestamp = -1777955776
LOG:      BMP class = 64
LOG:  pgaudit extension initialized
```

* If an incorrect timestamp literal is set, a value such as ```TMS timestamp = -1777955776``` is implicitly set.

**Comment by harada-toshi** [comment]
* Newly found matter.
  * The value set in TMS timestamp is different each time it is started.
  * This may be referencing an uninitialized area, so you should fix it.

(Japanese)
* 新たに判明した事項。
  * 起動するたびにTMS timestampに設定される値が異なります。
  * これは初期化されていない領域を参照している可能性があるため、修正すべきです。

**Comment by MasahikoSawada** [comment]
Thanks!
The commit 01c81ba5076185a63ccdd94a9efe7315965ab8dc should fix it.

**Comment by harada-toshi** [comment]
(Described in Japanese)

timestamp指定の以下のケースについてはエラーになることを確認しました。
* 英字を指定
* 日本語を指定
* HHが範囲(00～59)外のものを指定
* MMが範囲(00～59)外のものを指定

ただし、SSの範囲は(00～59)ではなく、(00～60)になるらしく60を指定した場合には、エラーにならず60秒が加算されるようです。
これは仕様どおりなんでしょうか（うるう秒のケースを想定している？）

* 設定ファイル
```
[rule]
        class = 'READ'
        timestamp = '01:00:00-08:00:60'
```

* 起動ログ抜粋
```
LOG:  Rule 0
LOG:      TMS timestamp = 3600000000
LOG:      TMS timestamp = 28860000000
LOG:      BMP class = 64
```

SSを61にするときちんろエラーにするので、SSについては60までを許容するというのが、PostgreSQLの仕様なのでしょうね。

**Comment by harada-toshi** [comment]
I have confirmed the timestamp specification error case.
* Specify the letter
* Specify Japanese
* Specify one whose HH is out of range (other than 00 to 59)
* Specify one whose MM is out of range (other than 00 to 59)
* Specify one whose SS is out of range (other than 00 to 60)
* There is no time designation on the left side
* There is no time designation on the right side
* The time designation on the right side is smaller than the time designation on the left side
* Time designation on the right side is the same as designation on the right side


Thank you for fixing.
This Issue is closed.

----
(Described in Japanese)

timestampの指定誤りケースを確認しました。
* 英字を指定
* 日本語を指定
* HHが範囲外のもの(00～59以外)を指定
* MMが範囲外のもの(00～59以外)を指定
* SSが範囲外のもの(00～60以外)を指定
* 左側の時刻指定がない
* 右側の時刻指定がない
* 右側の時刻指定が、左側時刻指定より小さい
* 右側の時刻指定が、右側時刻指定と同じ

修正ありがとうございます。
このIssueはクローズします。
