### ISSUE TITLE
unnecessary "AUDIT:" prefix is logged when database started. 

### ISSUE THREAD

**Issue by ooyamams** [ossc-db/pgaudit#7]
I want to log about "foo" database only. but it also log "database system was shut down" and "database system is ready to accept connections".

pgaudit.conf

```
[output]
logger= 'serverlog'

[rule]
database = 'foo'
class = 'READ'
```

postgresql.log

```
LOG:  AUDIT: SESSION,,,SYSTEM,database system was shut down at 2016-08-11 10:24:29 JST
LOG:  database system was shut down at 2016-08-11 10:24:29 JST
LOG:  MultiXact member wraparound protections are now enabled
LOG:  AUDIT: SESSION,,,SYSTEM,database system is ready to accept connections
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```

**Comment by MasahikoSawada** [comment]
The `class` rule is incomplete so far, it alway return true regardless value.
And postgres can have multiple database in a database cluster, so the starting postgres means that all databases in database cluster start and ready to accept connections.
It's impossible to emit the "database system was shut down" log or "ready to accept connections" log for particular database.

After supported `class` rule, you can filter them using by 'SYSTEM'.

**Comment by ooyamams** [comment]
Ok, it's not reproduce. Close.
